# Build 'latest' tag from main or master branches.
trigger:
  branches:
    include:
      - main
      - master
  tags:
    exclude:
      - "*"

resources:
  - repo: self

variables:
  dockerRegistry: "Docker Cloud - dfdsazuredevops" # Service Connection
  dockerOrganization: "dfdsdk"
  repository: "hello" # You need to specify the name for your image repository. For instance: hello
  imageName: "$(dockerOrganization)/$(repository)"

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: $(dockerRegistry)
              command: "login"
              addPipelineData: false
          - task: Docker@2
            displayName: Build an image
            inputs:
              repository: $(imageName)
              command: build
              Dockerfile: Dockerfile
              tags: |
                latest
          - task: Docker@2
            displayName: Push image
            inputs:
              containerRegistry: $(dockerRegistry)
              repository: $(imageName)
              command: push
              tags: |
                latest
